name: Run Python Script

# Definir quando esse workflow será executado
on:
  schedule:
    - cron: '0 9 * * *'   # 09:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
    - cron: '0 21 * * *'  # 21:00 UTC
  workflow_dispatch:

# Definir jobs que serão executados
jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Usa o ambiente Ubuntu mais recente

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3  # Faz checkout do código no repositório

    - name: Configurar Python
      uses: actions/setup-python@v4  # Instala Python
      with:
        python-version: '3.10'  # Define a versão do Python

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Instalar dependências necessárias (requests)

    - name: Rodar o script Python
      run: |
        python bot.py  # Substitua pelo nome do seu arquivo Python
      env:
        URL_ENDPOINT: ${{ secrets.URL_ENDPOINT }}  # Configurações sensíveis como variáveis de ambiente
        API_KEY: ${{ secrets.API_KEY }}
        MOEDA_VALOR: ${{ secrets.MOEDA_VALOR }}
        MOEDA_BUY: ${{ secrets.MOEDA_BUY }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
