name: Run Python Script Thrice Daily

on:
  schedule:
    - cron: '*/20 * * * *'   # A cada 20 minutos
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar o script Python
        run: |
          python bot.py
        env:
          URL_ENDPOINT: ${{ secrets.URL_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
          MOEDA_VALOR: ${{ secrets.MOEDA_VALOR || 'USD' }}  # Valor padrão USD
          MOEDA_BUY: ${{ secrets.MOEDA_BUY || 'BRL' }}    # Valor padrão BRL
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
